export default {

    SHOW_OR_HIDE_NAVIGATION: "SHOW_OR_HIDE_NAVIGATION",
    USER_LOGIN: 'USER_LOGIN',
    USER_SIGN_UP: 'USER_SIGN_UP',
    NO_USER:"NO_USER",
    USER_IS_LOGIN:"USER_IS_LOGIN",
    GET_USER:"GET_USER",
    SET_USER:"SET_USER",
    IS_LOGIN_ERROR:"IS_LOGIN_ERROR",

};